"""CJR-Swarm-Orchestrator — Pydantic v2 schema definitions.

This module defines every data contract used across the four-agent swarm
pipeline (Planner → Implementer → QA Reviewer → Git Controller).  All models
use strict Pydantic v2 validation so that malformed payloads are caught at
the boundary rather than deep inside agent logic.
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from enum import Enum
from typing import Optional
from uuid import UUID, uuid4

from pydantic import (
    BaseModel,
    Field,
    SecretStr,
    computed_field,
    field_validator,
    model_validator,
)


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class AgentRole(str, Enum):
    """Roles that an agent can assume in the swarm pipeline."""

    PLANNER = "PLANNER"
    IMPLEMENTER = "IMPLEMENTER"
    QA_REVIEWER = "QA_REVIEWER"
    GIT_CONTROLLER = "GIT_CONTROLLER"


class TaskPriority(str, Enum):
    """Priority levels for atomic tasks."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class TaskStatus(str, Enum):
    """Lifecycle states for an individual task."""

    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    RETRYING = "RETRYING"


class PipelineStage(str, Enum):
    """High-level stages of the swarm pipeline."""

    PLANNING = "PLANNING"
    IMPLEMENTATION = "IMPLEMENTATION"
    QA_REVIEW = "QA_REVIEW"
    GIT_PUSH = "GIT_PUSH"
    DONE = "DONE"


# ---------------------------------------------------------------------------
# Task & Plan models
# ---------------------------------------------------------------------------

class AtomicTask(BaseModel):
    """A single, indivisible unit of work produced by the Planner agent."""

    id: UUID = Field(default_factory=uuid4, description="Unique task identifier.")
    title: str = Field(..., description="Short, descriptive task title.")
    description: str = Field(..., description="Detailed description of what must be done.")
    priority: TaskPriority = Field(
        default=TaskPriority.MEDIUM,
        description="Execution priority.",
    )
    estimated_complexity: int = Field(
        ...,
        ge=1,
        le=10,
        description="Complexity estimate on a 1-10 scale.",
    )
    acceptance_criteria: list[str] = Field(
        ...,
        description="Criteria that must be met for the task to be considered complete.",
    )
    dependencies: list[UUID] = Field(
        default_factory=list,
        description="IDs of tasks that must complete before this one.",
    )


class ImplementationPlan(BaseModel):
    """The complete plan produced by the Planner agent for a feature."""

    project_name: str = Field(..., description="Name of the target project.")
    feature_objective: str = Field(..., description="High-level feature description.")
    tasks: list[AtomicTask] = Field(
        ...,
        min_length=1,
        description="Ordered list of atomic tasks.",
    )
    architecture_notes: str = Field(
        ...,
        description="Free-form architecture and design notes.",
    )
    tech_stack: list[str] = Field(
        ...,
        description="Technologies and libraries to be used.",
    )
    estimated_total_complexity: int = Field(
        default=0,
        description="Sum of all task complexity estimates (auto-computed).",
    )
    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of plan creation.",
    )

    @model_validator(mode="after")
    def _compute_total_complexity(self) -> "ImplementationPlan":
        self.estimated_total_complexity = sum(
            task.estimated_complexity for task in self.tasks
        )
        return self


# ---------------------------------------------------------------------------
# Code-generation models
# ---------------------------------------------------------------------------

class CodeFile(BaseModel):
    """A single source file generated by the Implementer agent."""

    filepath: str = Field(..., description="Relative path for the generated file.")
    content: str = Field(..., description="Full file content.")
    language: str = Field(default="python", description="Programming language.")

    @field_validator("filepath", mode="after")
    @classmethod
    def _validate_filepath(cls, v: str) -> str:
        if v.startswith("/"):
            raise ValueError(
                f"filepath must be relative, not absolute (got '{v}')."
            )
        if ".." in v:
            raise ValueError(
                f"filepath must not contain '..' path traversal (got '{v}')."
            )
        return v


class CodePayload(BaseModel):
    """Bundle of code files produced by the Implementer agent for one plan."""

    plan_id: UUID = Field(..., description="ID of the originating ImplementationPlan.")
    files: list[CodeFile] = Field(
        ...,
        min_length=1,
        description="Generated source files.",
    )
    entry_point: str = Field(
        ...,
        description="Primary file to execute (e.g. 'main.py').",
    )
    dependencies_added: list[str] = Field(
        default_factory=list,
        description="Any new pip packages required by the generated code.",
    )
    implementation_notes: str = Field(
        ...,
        description="Implementer's notes on design decisions or caveats.",
    )


# ---------------------------------------------------------------------------
# QA / Testing models
# ---------------------------------------------------------------------------

class TestCase(BaseModel):
    """A test case written by the QA Reviewer agent."""

    name: str = Field(..., description="Test function / case name.")
    test_code: str = Field(..., description="Full pytest-compatible test source.")
    target_file: str = Field(..., description="Source file under test.")
    expected_outcome: str = Field(
        default="pass",
        description="Expected result: 'pass' or a description of expected failure.",
    )


class TestResult(BaseModel):
    """Result of executing a single test case."""

    test_name: str = Field(..., description="Name of the executed test.")
    passed: bool = Field(..., description="Whether the test passed.")
    error_message: Optional[str] = Field(
        default=None,
        description="Error / traceback if the test failed.",
    )
    execution_time_ms: float = Field(
        ...,
        description="Wall-clock execution time in milliseconds.",
    )
    stdout: str = Field(default="", description="Captured standard output.")


class QAReport(BaseModel):
    """Aggregated QA report produced by the QA Reviewer agent."""

    payload_id: UUID = Field(
        ...,
        description="ID linking back to the CodePayload under review.",
    )
    test_cases: list[TestCase] = Field(
        ...,
        description="Test cases that were generated.",
    )
    test_results: list[TestResult] = Field(
        ...,
        description="Execution results for each test case.",
    )
    overall_passed: bool = Field(
        ...,
        description="True if all quality gates were met.",
    )
    coverage_estimate: float = Field(
        ...,
        ge=0,
        le=100,
        description="Estimated code coverage percentage (0-100).",
    )
    issues_found: list[str] = Field(
        ...,
        description="List of issues discovered during review.",
    )
    recommendations: list[str] = Field(
        ...,
        description="Actionable recommendations for improvement.",
    )
    retry_required: bool = Field(
        ...,
        description="Whether the pipeline should retry implementation.",
    )

    @computed_field  # type: ignore[misc]
    @property
    def pass_rate(self) -> float:
        """Fraction of tests that passed (0.0 – 1.0)."""
        if not self.test_results:
            return 0.0
        return sum(1 for r in self.test_results if r.passed) / len(self.test_results)


# ---------------------------------------------------------------------------
# Git models
# ---------------------------------------------------------------------------

class CommitInfo(BaseModel):
    """Metadata for a Git commit created by the Git Controller agent."""

    message: str = Field(..., description="Commit message (first line ≤ 72 chars).")
    files_changed: list[str] = Field(
        ...,
        description="Relative paths of files included in the commit.",
    )
    branch: str = Field(default="main", description="Target branch.")
    author: str = Field(
        default="CJR-Swarm-Agent <swarm@cjrcoder.dev>",
        description="Git author string.",
    )

    @field_validator("message", mode="after")
    @classmethod
    def _validate_commit_message(cls, v: str) -> str:
        first_line = v.split("\n", 1)[0]
        if len(first_line) > 72:
            raise ValueError(
                f"Commit message first line must be ≤ 72 characters "
                f"(got {len(first_line)})."
            )
        return v


class GitPushResult(BaseModel):
    """Result of a Git push operation."""

    success: bool = Field(..., description="Whether the push succeeded.")
    commit_sha: Optional[str] = Field(
        default=None,
        description="SHA of the created commit, if successful.",
    )
    remote_url: str = Field(..., description="Remote URL that was pushed to.")
    error_message: Optional[str] = Field(
        default=None,
        description="Error details if the push failed.",
    )
    pushed_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp of the push.",
    )


# ---------------------------------------------------------------------------
# Pipeline state
# ---------------------------------------------------------------------------

class ActionState(BaseModel):
    """Mutable state object that tracks the entire pipeline run."""

    pipeline_id: UUID = Field(
        default_factory=uuid4,
        description="Unique identifier for this pipeline execution.",
    )
    current_stage: PipelineStage = Field(
        default=PipelineStage.PLANNING,
        description="Current pipeline stage.",
    )
    feature_objective: str = Field(
        ...,
        description="The feature being built in this pipeline run.",
    )
    plan: Optional[ImplementationPlan] = Field(
        default=None,
        description="Plan produced by the Planner agent.",
    )
    code: Optional[CodePayload] = Field(
        default=None,
        description="Code produced by the Implementer agent.",
    )
    qa_report: Optional[QAReport] = Field(
        default=None,
        description="QA report produced by the QA Reviewer agent.",
    )
    git_result: Optional[GitPushResult] = Field(
        default=None,
        description="Result of the Git push operation.",
    )
    retries: int = Field(
        default=0,
        le=3,
        description="Number of retry attempts (max 3).",
    )
    started_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="UTC timestamp when the pipeline started.",
    )
    completed_at: Optional[datetime] = Field(
        default=None,
        description="UTC timestamp when the pipeline finished.",
    )
    error_log: list[str] = Field(
        default_factory=list,
        description="Chronological log of errors encountered.",
    )

    # -- helpers -------------------------------------------------------------

    def is_terminal(self) -> bool:
        """Return ``True`` if the pipeline has reached a terminal state."""
        return self.current_stage == PipelineStage.DONE or self.retries > 3

    def mark_complete(self) -> None:
        """Transition the pipeline to the DONE stage."""
        self.current_stage = PipelineStage.DONE
        self.completed_at = datetime.now(timezone.utc)

    def log_error(self, msg: str) -> None:
        """Append a timestamped error message to the error log."""
        timestamp = datetime.now(timezone.utc).isoformat()
        self.error_log.append(f"[{timestamp}] {msg}")


# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------

class SwarmConfig(BaseModel):
    """Runtime configuration for the swarm, loaded from environment variables."""

    nvidia_api_key: SecretStr = Field(
        ...,
        description="NVIDIA API key for DeepSeek model access.",
    )
    gemini_api_key: SecretStr = Field(
        ...,
        description="Google Gemini API key.",
    )
    gh_pat: SecretStr = Field(
        ...,
        description="GitHub Personal Access Token with repo scope.",
    )
    nvidia_base_url: str = Field(
        default="https://integrate.api.nvidia.com/v1",
        description="Base URL for the NVIDIA API.",
    )
    nvidia_model: str = Field(
        default="deepseek-ai/deepseek-coder-7b-instruct-v1.5",
        description="NVIDIA-hosted model identifier.",
    )
    gemini_model: str = Field(
        default="gemini-2.0-flash",
        description="Gemini model identifier.",
    )
    llama_model: str = Field(
        default="meta/llama-3.1-8b-instruct",
        description="Llama model identifier on NVIDIA.",
    )
    max_retries: int = Field(
        default=3,
        description="Maximum pipeline retry attempts.",
    )
    target_repo_owner: str = Field(
        default="CJRCODER",
        description="GitHub org or user that owns the target repo.",
    )

    @classmethod
    def from_env(cls) -> "SwarmConfig":
        """Construct a ``SwarmConfig`` from environment variables.

        Required env vars:
            - ``NVIDIA_API_KEY``
            - ``GEMINI_API_KEY``
            - ``GH_PAT``

        Raises:
            KeyError: If a required environment variable is missing.
        """

        def _require(name: str) -> str:
            value = os.environ.get(name)
            if not value:
                raise KeyError(
                    f"Required environment variable '{name}' is not set. "
                    f"Please export it before running the swarm."
                )
            return value

        return cls(
            nvidia_api_key=SecretStr(_require("NVIDIA_API_KEY")),
            gemini_api_key=SecretStr(_require("GEMINI_API_KEY")),
            gh_pat=SecretStr(_require("GH_PAT")),
        )
